### ISSUE TITLE
Syntax error?

### ISSUE THREAD

**Issue by lucapinello** [LucaCappelletti94/ucsc_genomes_downloader#3]
Hi Luca,

I am trying your tool but I get this error on importing:

from ucsc_genomes_downloader import Genome

ucsc_genomes_downloader/genome.py", line 66
    assembly: str,
            ^
SyntaxError: invalid syntax

I am on Python2.7 and installed it via pip.

Any suggestions?

**Comment by LucaCappelletti94** [comment]
Hello Luca,

There is no support for Python2.7 nor it will ever be supported since it's past its deprecation date.

The error you are seeing is a python2.7 compatibility error.

The only solution would be for you to migrate to python 3.x.

I understand that this is not always feasible, so I would suggest you install on your user on the machine you are using (be it a server or a notebook) [Anaconda 3.7](https://www.anaconda.com/) that requires no sudo as it only installs python 3.x on your account.

Best of luck,
Luca

**Comment by lucapinello** [comment]
Thanks for the near real-time response! This makes sense. Maybe you could consider adding a small note on the README and modify the setup.py to require python>3.x.

**Comment by LucaCappelletti94** [comment]
Sure, you are right on both points. Will definitely do!
